### ISSUE TITLE
exitcheck.g and tee: is it hanging ?

### ISSUE THREAD

**Issue by jgmbenoit** [gap-packages/io#40] opened 2016-01-19 15:02 UTC
I am on my way to write a Debian Continuous Integration [1] simple test based on the `run_tests.sh', its two last line more precisely.

The following command hangs:
$ echo "Read(\"/usr/share/gap/pkg/io/tst/testall.g\"); quit;" | gap | tee testlog.txt 

The following command does not hang but does not finish with a proper end-of-line
$ echo "Read(\"/usr/share/gap/pkg/io/tst/testall.g\"); quit;" | gap

This one does not hang but the last line does not have a proper end-of-line (according to cat -A)
$  echo "Read(\"/usr/share/gap/pkg/io/tst/testall.g\"); quit;" | gap > testlog.txt

Are those behaviours  expected ?

Thanks,
Jerome

[1] https://ci.debian.net/doc/

**Comment by fingolfin** [comment] 2016-01-31 11:47
Side remark: if you run tests, you probbaly should suppress the banner (or even use quiet mode), break loop and loading packages -- e.g. run GAP via `gap -A -q -T`

To answer your question: I am not completely sure right now if the hang with the first command is *intentional* -- though what I can say is that it is caused by `exitcheck.g`, and it intentioanlly spawns subprocesses which run a loong time, in order to see whether we properly clean up after them (and whether we do so in finite time). The bit that surprises me is that `tee` makes a difference. But it's probbaly because it messes with the stdout stream of the GAP process...

Anyway, perhaps @ChrisJefferson can answer that quickly? He added the check in question.


If you are using a recent GAP version, you can use `FORCE_QUIT_GAP(0)` instead of `quit` to force GAP to exit without waiting for exit handlers.


As to the final question: I am not sure what you mean with "proper end-of-line". There is no end-of-line character at the end of the output there, aye... That's what that test does here, too. So, if that is what you meant, I guess it is the "expected behaviour" (in the sense that it behaves on my machine the same way)

**Comment by ChrisJefferson** [comment] 2016-02-12 13:17
I'm not sure what is going on here, which is annoying. I am not sure why the `tee` changes behaviour.

**Comment by fingolfin** [comment] 2017-07-05 20:07
Just rediscovered this bug *cough*.

Looking at the list of active processes, when the hang occurs, gap is not really active anymore. So it is `tee` which refuses to end. Seems like the pipe is not closing down -- but I thought just the fact that gap exited should automatically take care of that?!? I guess the gaps (no pun intended) in my Unix knowledge are showing here :-/

**Comment by fingolfin** [comment] 2017-09-19 17:45
Here's a wild guess: Running GAP chained with `tee`, GAP's stdout is not a terminal anymore, but rather a pipe.

Now, whenever we fork, the child process gets access to the same stdout, i.e. the reference count of the file handle / descriptor of the pipe is incremented. When GAP dies, but some of its children do not die, then the pipe will still have a non-zero ref count. Since `exitcheck.g` launches children that run for an hour, the command can end up hanging that long.

Quick verification: If I comment out these two lines in `exitcheck.g`, the hang goes away:
```
 x2 := IO_Popen("sleep", ["3600"],"w");
...
y2 := IO_Popen("sleep", ["3600"],"w");
```
Of course that's just a workaround; we probably can also break `IO_Popen(..., "r")` (by piping into GAP), and `IO_Popen2` (by redirecting GAP's stderr into a pipe).

So to fix that hang, I guess we must either reap all child processes when we exit; or else ensure that they do not inherit our stdout needlessly....

I wonder what happens in similar situations in e.g. python or ruby?

**Comment by fingolfin** [comment] 2017-09-19 17:55
I might actually be wrong about the `"r"` variant of `popen` having the same problem (I did not test it, just speculation)... Somebody should test this... thing is, I believe child processes *are* killed by default when the parent dies, unless they are detached.

Also, googling for "tee causes process to hang" produces tons of hits, so we are not the first to encounter this :-)

**Comment by ChrisJefferson** [comment] 2017-10-20 12:55
Coming back to this (should have looked a long time ago, sorry)

**Closed** 2017-11-07 23:48 UTC
Labels: bug
